---

- name: Check if java is installed
    
  command: java -version
    
  register: java_result
      
  ignore_errors: True

  

- debug:

   msg: "Failed - Java is not installed"
    
  when: java_result is failed
      
 


- debug:
     
   msg: "Success - Java is installed"
     
  when:  java_result is success
    
  



- name: install second repo
    
   shell:
      
      cmd: ansible-galaxy install  --roles-path . -r requirements2.yml
     
      chdir: /home/U65974/Java/
    
  when: java_result is failed
